version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    restart: on-failure
    environment:
      PROJECT_NAME: 'Covid Tracker API Server'
      PORT: '8080'
      IS_PRODUCTION: 'false'
      DB_CONN_STR: 'mongodb://db:27017/covidtracker?readPreference=primary&ssl=false'
      DB_NAME: 'covidtracker'
      CORONA_STATS_API: 'https://corona-virus-stats.herokuapp.com/api/v1/cases'
    depends_on:
      - db
  db:
    image: mongo:4.4.4-bionic
    environment:
      MONGO_INITDB_DATABASE: 'covidtracker'
    restart: always
    ports:
        - '27017:27017'