# Generated by Django 3.0.5 on 2021-06-23 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_cases', models.TextField(verbose_name='total_cases')),
                ('recovery_cases', models.TextField(verbose_name='recovery_cases')),
                ('death_cases', models.TextField(verbose_name='death_cases')),
                ('last_update', models.TextField(verbose_name='last_update')),
                ('currently_infected', models.TextField(verbose_name='currently_infected')),
                ('last_fetched_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CountryStatistics',
        ),
    ]
