# Generated by Django 3.0.5 on 2021-06-23 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapi', '0002_auto_20210624_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.TextField(verbose_name='country')),
                ('country_abbreviation', models.TextField(verbose_name='country_abbreviation')),
                ('total_cases', models.TextField(verbose_name='total_cases')),
                ('new_cases', models.TextField(verbose_name='new_cases')),
                ('total_deaths', models.TextField(verbose_name='total_deaths')),
                ('new_deaths', models.TextField(verbose_name='new_deaths')),
                ('total_recovered', models.TextField(verbose_name='total_recovered')),
                ('active_cases', models.TextField(verbose_name='active_cases')),
                ('serious_critical', models.TextField(verbose_name='serious_critical')),
                ('cases_per_mill_pop', models.TextField(verbose_name='cases_per_mill_pop')),
                ('flag', models.TextField(verbose_name='flag')),
            ],
        ),
    ]
